### ISSUE TITLE
Suggestion: Implement photon-lib library to backup seed with 2fa 

### ISSUE THREAD

**Issue by bitcoinuser** [RohanKapurDEV/paymint#1]
Suggestion: Implement photon-lib library to backup seed with 2fa 

https://github.com/photon-sdk/photon-lib

**Comment by RohanKapurDEV** [comment]
Hey @bitcoinuser! Sorry for seeing this so incredibly late. The project has moved onto the following repo here:

https://github.com/Paymint-Labs/Paymint

I'll definitely try looking into photon-lib for 2fa seed backup. Seems like a really interesting feature. If you have any more suggestions, feel free to leave an issue in the new repository. Going to close this one here for now!
